
services:
  php:
    build: 
      context: ..
      dockerfile: docker/dockerfile
    container_name: php_app
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.4
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_ROOT_PASSWORD: ""
      MARIADB_DATABASE: user_management
      MARIADB_USER: root
      MARIADB_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: ""
    depends_on:
      - db

volumes:
  db_data:
